# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd0a7e020113ffae1044f4580a64e894aefa87ced9c5154dd790350f75ae3a0920588230f749bdf6a98e30238c1e80797bf845fd3691e823e8217ef552598de3

test:
  secret_key_base: c1b0da4f97791e4ae90aa5639e67ab047ce7e2ce8a12957db37e7a6cdcbbcd063fe7708ce8933b2477af40529873ea789d29d3cba1c51c3ea7bb84d4ea003d3b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
